version: '2'

services:

  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BUILDDOC=OFF
        - BUILDSWIG=OFF
        - BUILDSWIGPYTHON=OFF
        - BUILDSWIGJAVA=OFF
        - BUILDSWIGNODE=OFF
        - USBPLAT=OFF
        - FIRMATA=OFF
        - ONEWIRE=OFF
        - JSONPLAT=OFF
        - IMRAA=OFF
        - FTDI4222=OFF
        - IPK=OFF
        - RPM=OFF
        - ENABLEEXAMPLES=OFF
        - INSTALLGPIOTOOL=OFF
        - INSTALLTOOLS=OFF
        - BUILDTESTS=OFF
        - CC=clang-3.8
        - CXX=clang++-3.8
        - NODE_VERSION=v4.1.2
    environment:
      - http_proxy
      - https_proxy
      - no_proxy

  doc:
    extends: main
    build:
      args:
        - BUILDDOC=ON
    command: make doc
    volumes:
      - ./build/html:/usr/src/app/build/html

  python2:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGPYTHON=ON
    command: make _python2-mraa

  python3:
    extends: python2
    command: make _python3-mraa

  java:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGJAVA=ON
        - CC=gcc-4.8
        - CXX=g++-4.8
    command: make mraajava

  node4:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGNODE=ON
        - NODE_VERSION=v4.1.2
        - CC=gcc-4.8
        - CXX=g++-4.8
    command: bash -c "source /root/.nvm/nvm.sh && nvm use v4.1.2 && make npmpkg && cd .. && node-gyp configure && node-gyp build"

  node5:
    extends: node4
    build:
      args:
        - NODE_VERSION=v5.12.0
        - CC=clang-3.8
        - CXX=clang++-3.8
    command: bash -c "source /root/.nvm/nvm.sh && nvm use v5.12.0 && make npmpkg && cd .. && node-gyp configure && node-gyp build"
